version: 2

workflows:
  version: 2
  default_workflow:
    jobs:
      - update_doc:
          filters:
            branches:
              only: master

jobs:
  update_doc:
    working_directory: ~/build
    docker:
      - image: squidfunk/mkdocs-material
    steps:
      - checkout
      - run:
          name: Update documentation
          command: |
            cd wiki
            ./toc_collector.sh
            mkdocs gh-deploy -m "deployed $CIRCLE_SHA1 with mkdocs [skip ci]"
