# Project information
site_name: 'сyber•Congress wiki'
site_description: 'Knowledge base of cyber•Congress'
site_author: 'cyber•Congress team'
edit_uri: https://github.com/cybercongress/congress/edit/master/wiki/docs

# Repository
repo_name: 'congress'
repo_url: 'https://github.com/cybercongress/congress'


# Copyright
copyright: 'WTFPL – Do What the Fuck You Want to Public License.'


# Configuration
theme:
  name: null
  custom_dir: 'theme_extend/material'
  font:
    text: 'Play'
    code: 'Play'
  favicon: 'img/favicon.svg'
  logo: 'img/logo.svg'
  language: 'en'
  palette:
    primary: 'green'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/cybercongress'

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/progressbar.css'
extra_javascript:
  - https://unpkg.com/mermaid@7.1.0/dist/mermaid.min.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

      # Page tree
nav:
  - cyber•Congress: index.md
  - Contributing: contribute.md
#CYB table of content. Observe the correct tabulation. Do not change the tabulation of the header.
  - cyb:
    - Whitepaper: cyb/whitepaper.md
    - Requirements: cyb/requirements.md
    - Staging: cyb/staging.md
#cyberd table of content. Observe the correct tabulation. Do not change the tabulation of the header.
  - cyberd:
    - Overview: cyberd/cyberd.md
    - Roadmap: cyberd/Roadmap.md
    - Changelog: cyberd/Changelog.md
    - Contributing: cyberd/Contributing.md
#Changear table of content. Observe the correct tabulation. Do not change the tabulation of the header.
  - chaingear:
    - Overview: сhaingear/overview.md
    - Contracts: сhaingear/contracts.md
    - Pipelines: сhaingear/pipelines.md
    - Development: сhaingear/development.md
    - Changelog: сhaingear/Changelog.md
#cybernode table of content. Observe the correct tabulation. Do not change the tabulation of the header.
  - cybernode:
    - Overview: cybernode/cybernode.md
    - Components:
      - Requirements: cybernode/components/components-requirments.md
      - Chain-nodes: cybernode/components/chain-nodes-components.md
      - Monitoring: cybernode/components/monitoring-components.md
    - Chains:
      - Bitcoin: cybernode/chains/bitcoin.md
      - Ethereum: cybernode/chains/ethereum.md
    - Requirements: cybernode/requirements.md
    - Dev-setup: cybernode/dev-setup.md
    - Staging:
      - Chains: cybernode/staging/chains.md
      - CD: cybernode/staging/continuous-delivery.md
      - Kubernetes: cybernode/staging/kubernetes.md
      - Run: cybernode/staging/run.md
      - Setup: cybernode/staging/setup.md
    - Cheat-sheet: cybernode/k8s-cheat-sheet.md
#cyber-markets table of content. Observe the correct tabulation. Do not change the tabulation of the header.
  - cyber-markets:
    - Overview: cyber-markets/cyber-markets.md
    - API:
      - Readme: cyber-markets/api/Readme.md
    - Components:
      - Overview: cyber-markets/components/overview.md
    - Contributing:
      - Cheat-sheet: cyber-markets/contributing/cheat-sheet.md
      - Dev-environment: cyber-markets/contributing/dev-environment.md
      - Contributing: cyber-markets/contributing/contributing.md
#Cyber-search table of content. Observe the correct tabulation. Do not change the tabulation of the header.
  - cyber-search:
    - Overview: cyber-search/cyber-search.md
    - API:
      - Readme: cyber-search/api/README.md
    - Components:
      - Bitcoin: cyber-search/components/bitcoin-components.md
      - Ethereum: cyber-search/components/ethereum-components.md
      - Cassandra: cyber-search/components/cassandra-service.md
      - Custom chain name: cyber-search/components/custom-chain-name.md
      - Search-common:  cyber-search/components/search-common-components.md
    - Contributing:
      - Dev-environment: cyber-search/contributing/dev-environment.md
      - Pump-development: cyber-search/contributing/pump-development.md
      - Cheat-sheet: cyber-search/contributing/cheat-sheet.md
      - Contributing: cyber-search/contributing/contributing.md
#Cyb-js table of content. Observe the correct tabulation. Do not change the tabulation of the header.
  - cyb-js:
    - Overview: cyb-js/cyb-js.md
