# Copyright (c) 2016-2019 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: cyber•Congress
site_description: knowledge base of cyber•Congress
site_author: cyber•Congress
site_url: https://wiki.cybercongress.ai/

# Repository
repo_name: cyber•Congress
repo_url: https://github.com/cybercongress/congress
edit_uri: https://github.com/cybercongress/Library/wiki/docs

# Copyright
copyright: 'Cyber License - Don’t believe, don’t fear, don’t ask.'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: green
    accent: green
  font:
    text: Play
    code: Play Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo.svg

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/cybercongress/congress#cybercongress-the-evolution-of-species
    - type: twitter
      link: https://twitter.com/cyber_devs
    - type: reddit
      link: https://www.reddit.com/r/cybercongress/
    - type: telegram
      link: https://t.me/fuckgoogle
extra_css:
  - 'stylesheets/extra.css'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - blog: blog/blog.md
  - Ultimate cyberd CLI guide. Testnet Euler-1: blog/ultimate-commands-guide/ultimate-commands-guide.md
  - The show must go on: blog/sprint-27-report/sprint-27-report.md
  - Ultimate cyberd validator setup. Testnet Euler-1: blog/ultimate-validator-guide/ultimate-validator-guide.md
  - cyberd. Computing the knowledge from web3: 1.md
  - Let's code in paradise: blog/sprint-26-report/sprint-26-report.md
  - 42: blog/sprint-25-report/sprint-25-report.md
  - Sacred Rave: blog/sprint-24-report/sprint-24-report.md
  - How to play Dragonereum on Cyb: blog/dragons_with_cyb/dragons.md
  - How to import ETH wallet from Metamask to Cyb: blog/cyb_tutorial_metamask_import/metamask_import.md
  - First Week in Dragonereum: 1.md
  - How to add own ETH node to your Cyb: blog/cyb_tutorial_eth_local_node/eth_node.md
  - Invitation to cyberc0n. Distributed search conference organized by a code: 1.md
  - An idea of decentralized search for web3: 1.md
  - How to add own ipfs node to your Cyb: blog/cyb_tutorial_ipfs_local_node/ipfs_local_node.md
  - Dragonereum. Why you will want at least one DRAGON?: 1.md
  - Organic growth: blog/sprint-23-report/sprint-23-report.md
  - How to open ipfs link using Cyb?: blog/cyb_tutorial_ipfs_links/how_to_open_ipfs_hash.md
  - \> gitcoin lovers: blog/gitcoin_wf_announcement/announce.md
  - Never had it before and there it is again: blog/sprint-21-22-report/sprint-21-22-report.md
  - Thorny path of open source development: blog/sprint-20-report/sprint-20-report.md
  - The awaking of cyber•Congress: blog/sprint-19-report/sprint-19-report.md
  - \> cyber hello cybercongress: 1.md
#CYB table of content. Observe the correct tabulation. Do not change the tabulation of the header.
  - cyb:
    - Whitepaper: cyb/cyb.md
    - Web3 vision: cyb/web3-vision.md
    - App guidelines: cyb/app-guidelines.md
#cyberd table of content. Observe the correct tabulation. Do not change the tabulation of the header.
  - cyberd:
    - Whitepaper: cyberd/cyberd.md
    - Overview: cyberd/overview.md
    - Get CYB: cyberd/get_CYB.md
    - RPC: cyberd/rpc.md
    - Bandwidth Specification: cyberd/bandwidth.md
    - Contributing: cyberd/Contributing.md
    - Changelog: cyberd/Changelog.md
    - Help:
      - Run validator: cyberd/help/run_validator.md
#Changear table of content. Observe the correct tabulation. Do not change the tabulation of the header.
  - chaingear:
    - Overview: сhaingear/overview.md
    - Contracts: сhaingear/contracts.md
    - Pipelines: сhaingear/pipelines.md
    - Changelog: сhaingear/Changelog.md
    - Help:
      - Development: сhaingear/help/development.md
  - congress: index.md
  - Contributing: contribute.md
